version: "3.9"
services:
  privategpt:
    build: .
    image: privategpt:test
    command: [ "python", "src/privateGPT.py" ]
    environment:
      - PERSIST_DIRECTORY=${PERSIST_DIRECTORY:-/home/privategpt/db}
      - LLAMA_EMBEDDINGS_MODEL=${LLAMA_EMBEDDINGS_MODEL:-/home/privategpt/models/ggml-model-q4_0.bin}
      - MODEL_TYPE=${MODEL_TYPE:-GPT4All}
      - MODEL_PATH=${MODEL_PATH:-/home/privategpt/models/ggml-gpt4all-j-v1.3-groovy.bin}
      - MODEL_N_CTX=${MODEL_N_CTX:-1000}
    volumes:
      - ${MODEL_MOUNT:-./models}:/home/privategpt/models
      - ${PERSIST_MOUNT:-./db}:/home/privategpt/db
